## Author: Sambit K. Mishra
## Created: 02-06-2021

## Location for data and samples
DATADIR: /mnt/c/Users/sambi/Dropbox/My_Projects/001_corona_virus/05_RNA_Seq_proj_1/
SAMPLEDIR: /mnt/c/Users/sambi/Dropbox/My_Projects/001_corona_virus/05_RNA_Seq_proj_1/samples/

# Data source
src_url: https://sra-pub-sars-cov2.s3.amazonaws.com/sra-src/

SRR_CONTROL:
  - SRR12023943
  - SRR12023944
  - SRR12023945
SRR_TREATMENT:  
  - SRR12023946
  - SRR12023947
  - SRR12023948

# PARAMETERS
THREADS: 7

# SAMPLE NAMES
CONTROL:
  - Control1
  - Control2
  - Control3

TREATMENT:
  - 48hrs1
  - 48hrs2
  - 48hrs3
  

  # SAMPLE NAMES
# CONTROL:
#   - Control1_R1.fq.gz.1
#   - Control1_R2.fq.gz.1
#   - Control2_R1.fq.gz.1
#   - Control2_R2.fq.gz.1
#   - Control3_R1.fq.gz.1
#   - Control3_R2.fq.gz.1
# TREATMENT:
#   - 48hrs1_R1.fq.gz.1
#   - 48hrs1_R2.fq.gz.1
#   - 48hrs2_R1.fq.gz.1
#   - 48hrs2_R2.fq.gz.1
#   - 48hrs3_R1.fq.gz.1
#   - 48hrs3_R2.fq.gz.1 